/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-28 00:00:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import order.OrderManageBean;
import order.OrderManageDBBean;

public final class order_005fedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("order.OrderManageBean");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("order.OrderManageDBBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');

	OrderManageDBBean omdb = OrderManageDBBean.getInstance();
	OrderManageBean omb = omdb.getOrder(Long.parseLong(request.getParameter("o_dNum")));
	String pageNum = request.getParameter("pageNum");
	if(pageNum == null){
		pageNum = "1";
	}
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");
	String o_dStat = request.getParameter("o_dStat");
	int p_count = omb.getProduct_count();
	int p_price = omb.getProduct_price();
	String shipment;
	if(omb.getShipment() == null){
		shipment = "";
	} else{
		shipment = omb.getShipment();
	}

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>document</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body class=\"vertical  dark  \">\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("              <h2 class=\"page-title\">주문서 수정</h2>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                  <div class=\"card shadow mb-4\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                      <strong class=\"card-title\">주문 내역</strong>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <form action=\"order_edit_ok.jsp?pageNum=");
      out.print( pageNum );
      out.write("\" method=\"post\" name=\"order_frm\">\r\n");
      out.write("                        <div class=\"form-row\">\r\n");
      out.write("                          <div class=\"form-group col-md-3\">\r\n");
      out.write("                            <label for=\"date\">주문 일자</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"date\" value=\"");
      out.print( sdf.format(omb.getOrder_date()) );
      out.write("\" readonly />\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"form-group col-md-3\">\r\n");
      out.write("                            <label for=\"number\">주문 번호</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"order_number\" id=\"number\" value=\"");
      out.print( omb.getOrder_number() );
      out.write("\" readonly />\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"form-group col-md-3\">\r\n");
      out.write("                            <label for=\"status\">주문 상태</label>\r\n");
      out.write("                            <select id=\"status\" class=\"form-control\" name=\"order_detail_status\">\r\n");
      out.write("	                            <option value=\"입금 완료\">입금 완료</option>\r\n");
      out.write("		                        <option value=\"배송 준비\">배송 준비</option>\r\n");
      out.write("		                        <option value=\"배송중\">배송중</option>\r\n");
      out.write("		                        <option value=\"배송 완료\">배송 완료</option>\r\n");
      out.write("		                        <option value=\"구매 확정\">구매 확정</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"form-group col-md-3\">\r\n");
      out.write("                            <label for=\"shipment\">운송장 번호</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"shipment\" id=\"shipment\" value=\"");
      out.print( shipment );
      out.write("\" onchange=\"statusChange()\" />\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-row\">\r\n");
      out.write("                          <div class=\"form-group col-md-3\">\r\n");
      out.write("                            <label for=\"userId\">주문자 ID</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"userId\" value=\"");
      out.print( omb.getUser_id() );
      out.write("\" readonly />\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"form-group col-md-3\">\r\n");
      out.write("                            <label for=\"productNumber\">상품 번호</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"productNumber\" value=\"");
      out.print( omb.getProduct_number() );
      out.write("\" readonly />\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"form-group col-md-3\">\r\n");
      out.write("                            <label for=\"count\">수량(개)</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"product_count\" id=\"count\" value=\"");
      out.print( p_count );
      out.write("\" readonly />\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"form-group col-md-3\">\r\n");
      out.write("                            <label for=\"price\">금액(원)</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"product_price\" id=\"price\" value=\"");
      out.print( p_price );
      out.write("\" readonly />\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-row\">\r\n");
      out.write("                          <div class=\"form-group col-md-3\">\r\n");
      out.write("                            <label for=\"receivername\">수령자</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"receiver_name\" id=\"receivername\" value=\"");
      out.print( omb.getReceiver_name() );
      out.write("\" />\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-row\">\r\n");
      out.write("                          <div class=\"form-group col-md-2\">\r\n");
      out.write("                          	<label for=\"phone\">전화번호</label>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-row\">\r\n");
      out.write("                          <div class=\"form-group col-md-2\">\r\n");
      out.write("                            <select id=\"phone\" class=\"form-control\" name=\"receiver_phone1\">\r\n");
      out.write("	                            <option value=\"010\">010</option>\r\n");
      out.write("		                        <option value=\"02\">02</option>\r\n");
      out.write("		                        <option value=\"031\">031</option>\r\n");
      out.write("		                        <option value=\"051\">051</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"form-group col-md-2\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"receiver_phone2\" value=\"");
      out.print( omb.getReceiver_phone2() );
      out.write("\" maxlength=\"4\" />\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"form-group col-md-2\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"receiver_phone3\" value=\"");
      out.print( omb.getReceiver_phone3() );
      out.write("\" maxlength=\"4\" />\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("	                    <div class=\"form-row\">\r\n");
      out.write("	                    	<div class=\"form-group col-md-3\">\r\n");
      out.write("                          		<label for=\"address\">수령 주소</label>\r\n");
      out.write("                          	</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-row\">\r\n");
      out.write("	                        <div class=\"form-group col-md-1\">\r\n");
      out.write("	                        	<input type=\"text\" class=\"form-control\" name=\"receiver_pcode\" id=\"sample4_postcode\" value=\"");
      out.print( omb.getReceiver_pcode() );
      out.write("\">\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                        <div class=\"form-group col-md-1\">\r\n");
      out.write("							<input type=\"button\" class=\"form-control\" onclick=\"sample4_execDaumPostcode()\" value=\"주소 변경\"><br>\r\n");
      out.write("                        	</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-row\">\r\n");
      out.write("	                        <div class=\"form-group col-md-4\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" name=\"receiver_raddr\" id=\"sample4_roadAddress\" value=\"");
      out.print( omb.getReceiver_raddr() );
      out.write("\">\r\n");
      out.write("								<input type=\"hidden\" class=\"form-control\" name=\"receiver_jibun\" id=\"sample4_jibunAddress\" value=\"");
      out.print( omb.getReceiver_jibun() );
      out.write("\">\r\n");
      out.write("								<span id=\"guide\" style=\"color:#999;display:none;\"></span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group col-md-4\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" name=\"receiver_detailaddr\" id=\"sample4_detailAddress\" value=\"");
      out.print( omb.getReceiver_detailaddr() );
      out.write("\">\r\n");
      out.write("								<input type=\"hidden\" id=\"sample4_extraAddress\" placeholder=\"참고항목\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("                        <div style=\"text-align:center;\">\r\n");
      out.write("	                        <input type=\"button\" class=\"btn btn-primary\" value=\"목록\" onclick=\"history.go(-1)\" />\r\n");
      out.write("	                        <input type=\"reset\" class=\"btn btn-primary\">\r\n");
      out.write("	                        <input type=\"button\" class=\"btn btn-primary\" value=\"수정\" onclick=\"check()\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </form>\r\n");
      out.write("                    </div> <!-- /. card-body -->\r\n");
      out.write("                  </div> <!-- /. card -->\r\n");
      out.write("                </div> <!-- /. col -->\r\n");
      out.write("              </div> <!-- /. end-section -->\r\n");
      out.write("            </div> <!-- .col-12 -->\r\n");
      out.write("          </div> <!-- .row -->\r\n");
      out.write("        </div> <!-- .container-fluid -->\r\n");
      out.write("    </div> <!-- .wrapper -->\r\n");
      out.write("	<script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"../js/admin.js\" charset=\"UTF-8\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("		/*주문 수정 페이지에서 넘겨 받은 주문 상태가 기본으로 선택되게 하는 스크립트(Jquery 필요)*/\r\n");
      out.write("		$(function(){\r\n");
      out.write("			$(\"#status > option[value='");
      out.print( o_dStat );
      out.write("']\").prop(\"selected\", true);\r\n");
      out.write("		});\r\n");
      out.write("		/* 변수를 받아야해서 스크립트 파일에 넣지 못함 */\r\n");
      out.write("	</script>\r\n");
      out.write("	<script type=\"text/javascript\"> \r\n");
      out.write("		$(\"#shipment\").on(\"change keyup paste\", function(){\r\n");
      out.write("			$(function(){\r\n");
      out.write("				$(\"#status > option[value='배송중']\").prop(\"selected\", true);\r\n");
      out.write("			});\r\n");
      out.write("		})\r\n");
      out.write("		//운송장 번호가 입력되면 주문 상태가 배송중으로 변경\r\n");
      out.write("	</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
