/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-22 01:19:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user_005flog;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.MemberDBBean;

public final class findPwResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.MemberDBBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <link rel=\"icon\" href=\"favicon.ico\">\r\n");
      out.write("    <title>Tiny Dashboard - A Bootstrap Dashboard Template</title>\r\n");
      out.write("    <!-- Simple bar CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/simplebar.css\">\r\n");
      out.write("    <!-- Fonts CSS -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Overpass:ital,wght@0,100;0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Icons CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/feather.css\">\r\n");
      out.write("    <!-- Date Range Picker CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/daterangepicker.css\">\r\n");
      out.write("    <!-- App CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/app-light.css\" id=\"lightTheme\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/app-dark.css\" id=\"darkTheme\" disabled>\r\n");
      out.write("  </head>\r\n");
      out.write("  <style>\r\n");
      out.write("   .login{font-size: 25px;}\r\n");
      out.write("   .found-id{color: yellow; font-weight: bold; font-size: 35px;}\r\n");
      out.write("   input#btnLogin{background-color: #1B68FF; border-color: #1B68FF; border-radius: 3px; width: 30%; height: 40px; font-size: 20px; color: white;}\r\n");
      out.write("   input#btnback{background-color: #1B68FF; border-color: #1B68FF; border-radius: 3px; width: 25%; height: 40px; font-size: 15px; color: white;}\r\n");
      out.write("   input#btnjoin{background-color: #1B68FF; border-color: #1B68FF; border-radius: 3px; width: 25%; height: 40px; font-size: 15px; color: white;}\r\n");
      out.write("  </style>\r\n");
      out.write("  ");

	String id = request.getParameter("id");
	String name = request.getParameter("name");
	String email = request.getParameter("email");
	
	MemberDBBean pw_check = new MemberDBBean();
	String lastPhone = MemberDBBean.getInstance().getMember(id).getUser_phone3();
	String ramdomNum = pw_check.getRamdomPassword(4);
	/* String lastPhone = pw_check.getMember(id).getUser_phone3(); */
	
	String ramPhon = ramdomNum + lastPhone;
	
	//int result = pw_check.pwCheckMember(ramPhon, id, name, email);
	int result = pw_check.pwCheckMember(ramPhon, id, name, email);

      out.write('\r');
      out.write('\n');
      out.print( email );
      out.write("\r\n");
      out.write("  <body class=\"light \">\r\n");
      out.write("    <div class=\"wrapper vh-100\">\r\n");
      out.write("      <div class=\"row align-items-center h-100\">\r\n");
      out.write("        <form class=\"col-lg-3 col-md-4 col-10 mx-auto text-center\" name=\"idsearch\" method=\"post\">\r\n");

 		if (result == 1) {

      out.write("\r\n");
      out.write("          <a class=\"navbar-brand mx-auto mt-2 flex-fill text-center\" href=\"./index.html\">\r\n");
      out.write("            <svg version=\"1.1\" id=\"logo\" class=\"navbar-brand-img brand-md\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" x=\"0px\" y=\"0px\" viewBox=\"0 0 120 120\" xml:space=\"preserve\">\r\n");
      out.write("              <g>\r\n");
      out.write("                <polygon class=\"st0\" points=\"78,105 15,105 24,87 87,87 	\" />\r\n");
      out.write("                <polygon class=\"st0\" points=\"96,69 33,69 42,51 105,51 	\" />\r\n");
      out.write("                <polygon class=\"st0\" points=\"78,33 15,33 24,15 87,15 	\" />\r\n");
      out.write("              </g>\r\n");
      out.write("            </svg>\r\n");
      out.write("          </a>\r\n");
      out.write("          <h1 class=\"h6 mb-3\">Find ID</h1>\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <a class=\"login\">회원님의 임시 비밀번호는</a>\r\n");
      out.write("            <div class =\"found-id\">");
      out.print( ramdomNum );
      out.write(" + 본인 휴대폰 뒷자리 4자</div>\r\n");
      out.write("            <a class=\"login\">입니다.</a>\r\n");
      out.write("          </div>        \r\n");
      out.write("          <input type=\"button\" id=\"btnLogin\" value=\"Login\" onClick =\"javascript:window.location='login.jsp'\"/>\r\n");

 		 } else {

      out.write("\r\n");
      out.write("		<div class = \"container\">\r\n");
      out.write("   	  	<div class = \"found-fail\">\r\n");
      out.write("	    <h4>  등록된 정보가 일치하지 않습니다 </h4>  \r\n");
      out.write("	    </div>\r\n");
      out.write("	    <div class = \"found-login\">\r\n");
      out.write(" 		    <input type=\"button\" id=\"btnback\" value=\"다시 찾기\" onClick=\"history.back()\"/>\r\n");
      out.write(" 		    <input type=\"button\" id=\"btnjoin\" value=\"회원가입\" onClick=\"javascript:window.location='register.jsp'\"/>\r\n");
      out.write("       	</div>\r\n");
      out.write("       </div>\r\n");

  }

      out.write(" \r\n");
      out.write("          <p class=\"mt-5 mb-3 text-muted\">© 2022</p>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/moment.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/simplebar.min.js\"></script>\r\n");
      out.write("    <script src='js/daterangepicker.js'></script>\r\n");
      out.write("    <script src='js/jquery.stickOnScroll.js'></script>\r\n");
      out.write("    <script src=\"js/tinycolor-min.js\"></script>\r\n");
      out.write("    <script src=\"js/config.js\"></script>\r\n");
      out.write("    <script src=\"js/apps.js\"></script>\r\n");
      out.write("    <script language=\"JavaScript\" src=\"javascript.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    <!-- Global site tag (gtag.js) - Google Analytics -->\r\n");
      out.write("    <script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-56159088-1\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("      window.dataLayer = window.dataLayer || [];\r\n");
      out.write("\r\n");
      out.write("      function gtag()\r\n");
      out.write("      {\r\n");
      out.write("        dataLayer.push(arguments);\r\n");
      out.write("      }\r\n");
      out.write("      gtag('js', new Date());\r\n");
      out.write("      gtag('config', 'UA-56159088-1');\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
