/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-29 02:36:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_005fnav_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String id = (String)session.getAttribute("id");
	String name = (String)session.getAttribute("name");
	String user_grade = "";
	int grade = 0;
	if(session.getAttribute("grade") == null){
		response.sendRedirect("main.jsp?pages=error");
	} else {
		user_grade = String.valueOf(session.getAttribute("grade"));
		grade = Integer.parseInt(user_grade);
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>main_nav</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<ul class=\"navbar-nav flex-fill w-100 mb-2\">\r\n");
      out.write("		 <li class=\"nav-item w-100\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"main.jsp\">\r\n");
      out.write("            <i class=\"fe fe-home fe-16\"></i>\r\n");
      out.write("            <span class=\"ml-3 item-text\">홈</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item w-100\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"main.jsp?pages=../order/order_body\">\r\n");
      out.write("            <i class=\"fe fe-truck fe-16\"></i>\r\n");
      out.write("            <span class=\"ml-3 item-text\">주문 조회</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a href=\"#ui-elements\" data-toggle=\"collapse\" aria-expanded=\"false\" class=\"dropdown-toggle nav-link\">\r\n");
      out.write("            <i class=\"fe fe-box fe-16\"></i>\r\n");
      out.write("            <span class=\"ml-3 item-text\">상품</span>\r\n");
      out.write("          </a>\r\n");
      out.write("         <ul class=\"collapse list-unstyled pl-4 w-100\" id=\"ui-elements\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link pl-3\" href=\"main.jsp?pages=../product/product_list&category_code=t-shirt\">\r\n");
      out.write("              <span class=\"ml-1 item-text\">티셔츠</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link pl-3\" href=\"main.jsp?pages=../product/product_list&category_code=hoodie\">\r\n");
      out.write("              <span class=\"ml-1 item-text\">후드티</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link pl-3\" href=\"main.jsp?pages=../product/product_list&category_code=knit\">\r\n");
      out.write("              <span class=\"ml-1 item-text\">니트/스웨터</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link pl-3\" href=\"main.jsp?pages=../product/product_list&category_code=shirt\">\r\n");
      out.write("              <span class=\"ml-1 item-text\">셔츠/남방</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link pl-3\" href=\"main.jsp?pages=../product/product_list&category_code=pants\">\r\n");
      out.write("              <span class=\"ml-1 item-text\">바지</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link pl-3\" href=\"main.jsp?pages=../product/product_list&category_code=blue-jeans\">\r\n");
      out.write("              <span class=\"ml-1 item-text\">청바지</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item w-100\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"main.jsp?pages=../cart/cartList\">\r\n");
      out.write("            <i class=\"fe fe-truck fe-16\"></i>\r\n");
      out.write("            <span class=\"ml-3 item-text\">장바구니</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item w-100\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"main.jsp?pages=../product/likeList\">\r\n");
      out.write("            <i class=\"fe fe-heart fe-16\"></i>\r\n");
      out.write("            <span class=\"ml-3 item-text\">나의 찜 목록</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item w-100\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"main.jsp?pages=../cs/cs_main\">\r\n");
      out.write("            <i class=\"fe fe-headphones fe-16\"></i>\r\n");
      out.write("            <span class=\"ml-3 item-text\">고객센터</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("    </ul>\r\n");
      out.write("    \r\n");
      out.write("	");

		if(session.getAttribute("Member") == null){ // 회원이 아닌 경우
	
      out.write("\r\n");
      out.write("		<a href=\"main.jsp?pages=../user_log/login\" class=\"btn mb-2 btn-primary btn-lg btn-block\" role=\"button\"><i class=\"fe fe-log-in fe-16\"></i> 로그인</a>\r\n");
      out.write("	    <a href=\"main.jsp?pages=../user_log/register\" class=\"btn mb-2 btn-secondary btn-lg btn-block\" role=\"button\"><i class=\"fe fe-user-plus fe-16\"></i> 회원가입</a>\r\n");
      out.write("	");

    	} else if(grade == 1) {
	
      out.write("\r\n");
      out.write("		<p><strong>안녕하세요 ");
      out.print( id );
      out.write(" 님</strong></p>\r\n");
      out.write("		<a href=\"../admin/adminIndex.jsp\" class=\"btn mb-2 btn-warning btn-lg btn-block\" role=\"button\"><i class=\"fe fe-log-in fe-16\"></i> 관리페이지</a>\r\n");
      out.write("	    <a href=\"../user_log/logout.jsp\" class=\"btn mb-2 btn-secondary btn-lg btn-block\" role=\"button\"><i class=\"fe fe-log-out fe-16\"></i> 로그아웃</a>\r\n");
      out.write("	");

		} else {
	
      out.write("\r\n");
      out.write("		<p><strong>안녕하세요 ");
      out.print( id );
      out.write("님</strong></p>\r\n");
      out.write("	    <a href=\"main.jsp?pages=../user_log/mypage\" class=\"btn mb-2 btn-primary btn-lg btn-block\" role=\"button\"><i class=\"fe fe-log-in fe-16\"></i> 마이페이지</a>\r\n");
      out.write("	    <a href=\"../user_log/logout.jsp\" class=\"btn mb-2 btn-secondary btn-lg btn-block\" role=\"button\"><i class=\"fe fe-log-out fe-16\"></i> 로그아웃</a>\r\n");
      out.write("    ");

    	}
    
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
