/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-28 07:13:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_005ffooter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("    * {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        list-style: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul.main_banner {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-around;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul.main_banner li a {\r\n");
      out.write("        width: 16%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    a {\r\n");
      out.write("        color: black;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul.menu1 {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-around;\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul.menuList {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul.menuList li {\r\n");
      out.write("        width: 23%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    li.foot_menu_d1 {\r\n");
      out.write("        width: 27%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    li.foot_menu_d2 {\r\n");
      out.write("        width: 15%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    li.foot_menu_d3 {\r\n");
      out.write("        width: 26%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    li.foot_menu_d4 {\r\n");
      out.write("        width: 28%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h4.title {\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    li.compay_phone {\r\n");
      out.write("        font-size: 45px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    a.btn_resp {\r\n");
      out.write("        border: 1px solid silver;\r\n");
      out.write("        padding: 3px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul.menu2 {\r\n");
      out.write("        display: flex;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul.menu2 li {\r\n");
      out.write("        margin-right: 50px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul.menu3 {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul.menu3 li {\r\n");
      out.write("        margin-bottom: 3px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    span.pcolor {\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    .margin_con {\r\n");
      out.write("    	margin-left: 1.25rem;\r\n");
      out.write("    }\r\n");
      out.write("    .margin_con .main_banner li img {\r\n");
      out.write("    	width:50%;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"margin_con\">\r\n");
      out.write("    <ul class=\"main_banner\">\r\n");
      out.write("        <li><a class=\"slink\" href=\"#\"><img class=\"simg\" src=\"../images/1.png\"></a></li>\r\n");
      out.write("        <li><a class=\"slink\" href=\"#\"><img class=\"simg\" src=\"../images/2.png\"></a></li>\r\n");
      out.write("        <li><a class=\"slink\" href=\"#\"><img class=\"simg\" src=\"../images/3.png\"></a></li>\r\n");
      out.write("        <li><a class=\"slink\" href=\"#\"><img class=\"simg\" src=\"../images/4.png\"></a></li>\r\n");
      out.write("        <li><a class=\"slink\" href=\"#\"><img class=\"simg\" src=\"../images/5.png\"></a></li>\r\n");
      out.write("        <li><a class=\"slink\" href=\"#\"><img class=\"simg\" src=\"../images/6.png\"></a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <div id=\"layout_footer\" class=\"layout_footer\">\r\n");
      out.write("        <div class=\"footer_a\">\r\n");
      out.write("            <div class=\"resp_wrap\">\r\n");
      out.write("                <ul class=\"menu1\">\r\n");
      out.write("                    <li class=\"foot_menu_d1\">\r\n");
      out.write("                        <h4 class=\"title\"><a href=\"/service/cs\" designelement=\"text\" textindex=\"1\"\r\n");
      out.write("                                texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">CS CENTER</a></h4>\r\n");
      out.write("                        <ul class=\"list v4\">\r\n");
      out.write("                            <li class=\"compay_phone\">\r\n");
      out.write("                                <a href=\"tel:02-535-6100\"><img src=\"/data/skin/20201008/images/common/icon_call_02.png\"\r\n");
      out.write("                                        class=\"img_call\" alt=\"\">02-535-6100</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <p designelement=\"text\" textindex=\"2\"\r\n");
      out.write("                                    texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">OPEN : AM 09:30\r\n");
      out.write("                                    - PM 06:30 / SAT, SUN, HOLIDAY OFF</p>\r\n");
      out.write("                                <p designelement=\"text\" textindex=\"3\"\r\n");
      out.write("                                    texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">영업시간외 문의는 카카오톡\r\n");
      out.write("                                    채널로 부탁드립니다</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <!-- //고객센터 -->\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"foot_menu_d2\">\r\n");
      out.write("                        <h4 class=\"title\"><span designelement=\"text\" textindex=\"4\"\r\n");
      out.write("                                texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">BANK INFO</span>\r\n");
      out.write("                        </h4>\r\n");
      out.write("                        <ul class=\"list v3 gray_03\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <p>신한 110-450-551224</p>\r\n");
      out.write("                                <p><span class=\"gray_06\" designelement=\"text\" textindex=\"5\"\r\n");
      out.write("                                        texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">예금주 :</span>\r\n");
      out.write("                                    그린샵</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <!-- //무통장 입금계좌 -->\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"foot_menu_d3\">\r\n");
      out.write("                        <h4 class=\"title\"><span designelement=\"text\" textindex=\"6\"\r\n");
      out.write("                                texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">SHOP MENU</span>\r\n");
      out.write("                        </h4>\r\n");
      out.write("                        <ul class=\"menuList\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"main.jsp?pages=../user_log/mypage\" ><img src=\"../images/2-1.png\" alt=\"\">\r\n");
      out.write("                                <p class=\"desc\" designelement=\"text\" textindex=\"7\"\r\n");
      out.write("                                    texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">마이페이지</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"main.jsp?pages=../cart/cartList\"><img src=\"../images/2-2.png\" alt=\"\">\r\n");
      out.write("                                <p class=\"desc\" designelement=\"text\" textindex=\"8\"\r\n");
      out.write("                                    texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">CART</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"main.jsp?pages=../cs/cs_main\"><img src=\"../images/2-3.png\" alt=\"\">\r\n");
      out.write("                                <p class=\"desc\" designelement=\"text\" textindex=\"9\"\r\n");
      out.write("                                    texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">CS CENTER</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"main.jsp?pages=../product/likeList\"><img src=\"../images/2-4.png\" alt=\"\">\r\n");
      out.write("                                <p class=\"desc\" designelement=\"text\" textindex=\"10\"\r\n");
      out.write("                                    texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">찜목록</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <!-- //게시판 -->\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"foot_menu_d4\">\r\n");
      out.write("                        <h4 class=\"title\"><span designelement=\"text\" textindex=\"11\"\r\n");
      out.write("                                texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">DELIVERY INFO</span>\r\n");
      out.write("                        </h4>\r\n");
      out.write("                        <ul class=\"list v5\">\r\n");
      out.write("                            <li><span designelement=\"text\" textindex=\"12\"\r\n");
      out.write("                                    texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">반품주소 :</span>\r\n");
      out.write("                                서울특별시 서초구 동광로10길 27 그린촬영시스템(주)</li>\r\n");
      out.write("                            <li style=\"text-indent:0; padding-left:0;\">\r\n");
      out.write("                                <span designelement=\"text\" textindex=\"13\"\r\n");
      out.write("                                    texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">배송조회 : 로젠택배\r\n");
      out.write("                                    1588-9988</span>&nbsp;\r\n");
      out.write("                                <a href=\"https://www.ilogen.com/web/personal/tkSearch\" target=\"_blank\" title=\"새창\"\r\n");
      out.write("                                    class=\"btn_resp\" designelement=\"text\" textindex=\"14\"\r\n");
      out.write("                                    texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\"\r\n");
      out.write("                                    alt=\"택배사 배송추적 주소를 입력하세요.\">배송추적</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <!-- //배송 정보 -->\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <div class=\"footer_b\">\r\n");
      out.write("            <div class=\"resp_wrap\">\r\n");
      out.write("                <ul class=\"menu2\">\r\n");
      out.write("                    <li><a href=\"/\" designelement=\"text\" textindex=\"15\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">HOME</a></li>\r\n");
      out.write("                    <li><a href=\"/service/company\" designelement=\"text\" textindex=\"16\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">COMPANY</a></li>\r\n");
      out.write("                    <li><a href=\"/service/agreement\" designelement=\"text\" textindex=\"17\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">AGREEMENT</a></li>\r\n");
      out.write("                    <li class=\"bold\"><a href=\"/service/privacy\" designelement=\"text\" textindex=\"18\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">PRIVACY POLICY</a></li>\r\n");
      out.write("                    <li><a href=\"/service/guide\" designelement=\"text\" textindex=\"19\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">GUIDE</a></li>\r\n");
      out.write("                    <li><a href=\"/service/partnership\" designelement=\"text\" textindex=\"20\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">PARTNER</a></li>\r\n");
      out.write("                    <li class=\"bold\"><a href=\"http://nisifilters.co.kr/main/index\" designelement=\"text\" textindex=\"21\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">\r\n");
      out.write("                            <p style=\"color:#fcaf15;\">NISI FILTERS KOREA</p>\r\n");
      out.write("                        </a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!-- //회사 링크 -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <div class=\"footer_c\">\r\n");
      out.write("            <div class=\"resp_wrap\">\r\n");
      out.write("                <ul class=\"menu3\">\r\n");
      out.write("                    <li><span designelement=\"text\" textindex=\"22\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">회사명 :</span> <span\r\n");
      out.write("                            class=\"pcolor\">그린샵(주)</span></li>\r\n");
      out.write("                    <li><span designelement=\"text\" textindex=\"23\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">대표자 :</span> <span\r\n");
      out.write("                            class=\"pcolor\">이홍섭 </span></li>\r\n");
      out.write("                    <li><span designelement=\"text\" textindex=\"24\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">주소 :</span> <span\r\n");
      out.write("                            class=\"pcolor\">서울특별시 서초구 동광로10길 27 그린샵(주)</span></li>\r\n");
      out.write("                    <li><span designelement=\"text\" textindex=\"25\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">전화 :</span> <a\r\n");
      out.write("                            href=\"tel:02-535-6100\" class=\"pcolor\">02-535-6100</a></li>\r\n");
      out.write("                    <li><span designelement=\"text\" textindex=\"26\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">팩스 :</span> <span\r\n");
      out.write("                            class=\"pcolor\">02-535-6230</span></li>\r\n");
      out.write("                    <li><span designelement=\"text\" textindex=\"27\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">사업자등록번호 :</span> <span\r\n");
      out.write("                            class=\"pcolor\">111-82-32270 <a href=\"javascript:;\"\r\n");
      out.write("                                onclick=\"window.open('https://www.ftc.go.kr/bizCommPop.do?wrkr_no=1148637270','communicationViewPopup','width=750,height=700,scrollbars=yes')\">[사업자정보확인]</a></span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><span designelement=\"text\" textindex=\"28\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">통신판매업신고번호 :</span> <span\r\n");
      out.write("                            class=\"pcolor\">2009-서울서초1176호</span></li>\r\n");
      out.write("                    <li><span designelement=\"text\" textindex=\"29\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">개인정보보호책임자 : </span>이홍섭\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><span designelement=\"text\" textindex=\"30\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">회사 이메일 : </span><span\r\n");
      out.write("                            class=\"pcolor\"><a class=\"pcolor\"\r\n");
      out.write("                                href=\"mailto:green@greenshop.co.kr\">green@greenshop.co.kr</a></span></li>\r\n");
      out.write("                    <li><span designelement=\"text\" textindex=\"31\"\r\n");
      out.write("                            texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">호스팅 제공자 :</span> <span\r\n");
      out.write("                            class=\"pcolor\">(주)가비아씨엔에스</span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <p class=\"copyright\" designelement=\"text\" textindex=\"32\"\r\n");
      out.write("                    texttemplatepath=\"MjAyMDEwMDgvbGF5b3V0X2Zvb3Rlci9zdGFuZGFyZC5odG1s\">COPYRIGHT (c) <span\r\n");
      out.write("                        class=\"pcolor\">그린샵(주)</span> ALL RIGHTS RESERVED.</p>\r\n");
      out.write("                <div class=\"escrow\"></div>\r\n");
      out.write("                <!-- //회사 정보 -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
